### ISSUE TITLE
reduced domain of operands compared to `Rational`

### ISSUE THREAD

**Issue by KlausC** [JeffreySarnoff/FastRationals.jl#1]
Operations overflow, if the intermediate products do not match `Int64`. That restricts the length of numerators / denominators to half of the possible in many cases:

```
julia> x = 2*10^10
20000000000
julia> 1//2x - 1//3x # Rational can handle this:
1//120000000000
julia> FastRational(1, 2x) - FastRational(1, 3x) # also error text contains '+' ??
ERROR: OverflowError: 1//40000000000 + 1//60000000000 overflowed
Stacktrace:
 [1] -(::FastRational{Int64,FastRationals.IsReduced}, ::FastRational{Int64,FastRationals.IsReduced}) at /home/crusius/.julia/dev/FastRationals/src/FastRationals.jl:282
 [2] top-level scope at REPL[39]:1

julia> ((x+1)//x) / ((x+1)//x) # should be easy
1//1
julia> FastRational(x+1, x) / FastRational(x+1, x) # also error text??
ERROR: OverflowError: 20000000001//20000000000 + 20000000001//20000000000 overflowed
Stacktrace:
 [1] /(::FastRational{Int64,FastRationals.IsReduced}, ::FastRational{Int64,FastRationals.IsReduced}) at /home/crusius/.julia/dev/FastRationals/src/FastRationals.jl:282
 [2] top-level scope at REPL[46]:1

```

**Comment by JeffreySarnoff** [comment]
I am fully aware of this -- my week is full of refactoring and logic verification .. I have been pulling it apart after adding too much.  It is has not been announced except to ask for some prerelease comments.  (of which yours are helpful and appreciated) I will put a note up on the readme while sorting this.

Actually I `revised` it into the current state -- and will `advise` it out again.

**Comment by JeffreySarnoff** [comment]
I am closing these issues with the understanding that you are encouraged to raise these or other issues that you may encounter after I have put the code as better works.
