### ISSUE TITLE
` hash` methods not properly defined

### ISSUE THREAD

**Issue by KlausC** [JeffreySarnoff/FastRationals.jl#10]
The ` hash` methods defined in FastQ32 and FastQ64 should be removed. Everything required should be `decompose` and the rest is done by `hash(::Real)` in ` Base` .

Otherwise the contract for `==`  and ` hash` would be violated.

` ` ` 
julia> FastQ64(1,2) == 1//2
true

julia> hash(FastQ64(1,2))
0x8e6df88ef289f361

julia> hash(1//2)
0x0d28115fab9910a5
` ` `

**Comment by JeffreySarnoff** [comment]
removed -- thank you
