### ISSUE TITLE
FastRationals.compactify_rational  vs. Base.rationalize

### ISSUE THREAD

**Issue by KlausC** [JeffreySarnoff/FastRationals.jl#13]
The exists already `Base.rationalize` to find a `Rational` closest to a given `AbstractFloat` with a given (optional) tolerance. Wouldn't it be nice to adapt to the naming / signature?

**Comment by JeffreySarnoff** [comment]
Possibly, at least it makes sense to provide that.  The intent/algorithm is different, though.  Thinking on it.

**Comment by JeffreySarnoff** [comment]
`rationalize` maps to a rational, not from a rational, so `FastRational(rationalize(...))` would be the way to use it.

**Comment by KlausC** [comment]
Yes, I saw that. But your implemetation of `compactify_rational` essentially converts its (Fast)-Rational arguments to floats and passes them to the private `compact_rational(lo, hi)`. The last one can be considered an algorithmic improvement of `Base.rationalize(mid; tol)`. So it would be awfull to improve `Base` with the better algorithm.

**Comment by JeffreySarnoff** [comment]
I do not understand the last sentence.

**Comment by KlausC** [comment]
The improved algorithm should replace that one in `Base.rationalize`. But that is a PR for `julia` not for `FastRationals`.
