### ISSUE TITLE
compactify_rational broken

### ISSUE THREAD

**Issue by KlausC** [JeffreySarnoff/FastRationals.jl#14]
When tolerance is too low, stack-overflow occurs.

```
julia> compactify_rational(FastRational(rationalize(float(pi))), FastQ64(2048, typemax(Int)))
165707065//52746197

julia> rationalize(float(pi))
165707065//52746197

julia> compactify_rational(FastRational(rationalize(float(pi))), FastQ64(1024, typemax(Int)))
ERROR: StackOverflowError:
Stacktrace:
 [1] compact_rational_unchecked(::Float64, ::Float64) at /home/crusius/.julia/dev/FastRationals/src/compactify.jl:57 (repeats 80000 times)
```

**Comment by JeffreySarnoff** [comment]
Thanks. Good Catch. Now it errors appropriately.  Compactify is intended to be used to reduce the denominator when the rational space is coarse and the rational denominators have become considerably larger than the coarseness. So, erroring on too fine a tolerance is appropriate.
