### ISSUE TITLE
has function still incorrect

### ISSUE THREAD

**Issue by KlausC** [JeffreySarnoff/FastRationals.jl#17]
We have the following:
```
julia> hash(FastRational(6, 9))  # wrong!
0x1e381bf2b0403fce
julia> hash(FastRational(2, 3))
0x36fc23415080622e
julia> hash(Rational(6, 9))
0x36fc23415080622e
```
Because 2//3 == 6//9 the second value is correct.

Reason is the generic implementation of `hash(x::Real, ...)` assumes that `Base.decompose` returns coprime numerator and denominator. For `FastRational` that is not the case.
That could be fixed as follows:

```
julia> Base.decompose(x::FastRational{T}) where T<:Union{Signed,Unsigned} = Base.decompose(x.num // x.den)
julia> hash(FastRational(6, 9))
0x36fc23415080622e
```

**Comment by JeffreySarnoff** [comment]
done

**Comment by KlausC** [comment]
That was really fast!!! :-)
