### ISSUE TITLE
negative denominators spoil comparison operating

### ISSUE THREAD

**Issue by KlausC** [JeffreySarnoff/FastRationals.jl#19]
We have the following:
```
julia> x = FastRational(-10, -20)
1//2
julia> y = FastRational(1, 1)
1//1
julia> x < y
false
```
Reason is, that the comparison operations silently assume, that the denominators are positive.
That could be fixed by forcing denominators positive within the inner constructor(s) by moving
`num, den = flipsign(num, den), abs(den)` from `canonical`.

```
function FastRational(num::T, den::T) where {T<:Union{Signed,Unsigned}}
      iszero(den) && throw(DivideError)
      num, den = flipsign(num, den), abs(den)
      return new{T}(num, den)
end
```

**Comment by JeffreySarnoff** [comment]
good point, or by checking

**Comment by KlausC** [comment]
I think the operations `flipsign` and `abs` are cheap enough to do them in the constructor.

I am not sure, if other methods also make the assumption of positiveness. So if we don't assure it in the constructor, we need test maybe many test cases for negative denoms.

**Comment by JeffreySarnoff** [comment]
This issue arose because `abs(typemin(IntN)) == typemin(IntN)` and I had thought about allowing the negative denominator, just did not carry that through the other routines.

**Comment by KlausC** [comment]
So it make sense to exclude ` typemin(...)` as a denominator.
BTW: Rational has the issue as well. [#32569](https://github.com/JuliaLang/julia/issues/32569)
