### ISSUE TITLE
I'd like to know where we lost some `FastQ64` relative speedup.

### ISSUE THREAD

**Issue by JeffreySarnoff** [JeffreySarnoff/FastRationals.jl#21]

**Comment by JeffreySarnoff** [comment]
@KlausC any idea?

**Comment by KlausC** [comment]
How do you collect the benchmark results? (which script, how started?) I would like to re-do the runs on my box.
I saw, that we have again 2 internal constructors, one without parameter checking. Plus many constructors as defined in `promote...jl`. Maybe for `Int32` different constructor from `Int64` used?

**Comment by JeffreySarnoff** [comment]
each benchmark script is linked in the README.md right where the respective benchmark results are listed.  All benchmark scripts are in 'FastRationals.jl/benchmarks'.  I am not at my computer right now.


Jeffrey Sarnoff

**Comment by JeffreySarnoff** [comment]
The reason for the additional constructors is that completely replacing those with the ones that you had led to ambiguity errors.
I kept all of your edits to that file except one, as I recall (isolating the ambiguity) and put back the ?four more specific ones to provide breadth without ambiguity.


Jeffrey Sarnoff

**Comment by JeffreySarnoff** [comment]
We do need two inner constructors as that helps performance. That one does not have the same workings as the other is probably a error of multiple edits.

Jeffrey Sarnoff

**Comment by JeffreySarnoff** [comment]
I can check the initializers called.

Jeffrey Sarnoff

**Comment by JeffreySarnoff** [comment]
Ok, the brief internal constructor is as intended.  The proper logical use may not yet carry throughout, nonetheless the purpose of that constructor is so we have an as-fast-as-possible construct when it is already known that the ` denominator > 0 `.

**Comment by JeffreySarnoff** [comment]
It may be better to use the tuple form for that purpose.

**Comment by JeffreySarnoff** [comment]
current master times reduce 32 bit to approximately match 64 bit.
So, perhaps, undoing the slowdown for 32 bits will undo the slowdown for both.
I will attempt to recover that speedup with minimal alteration tonight.
There are a couple of FIXMEs in the tests, I am letting those go until afterward (they are perhaps easy).

```
        relative speeds
         (32)    (64)

mul:     18.3    18.5
muladd:  15.9    15.4
add:     13.0    13.8
poly:    12.8    20.0
matmul:  10.0    11.4
matlu:   4.8     5.4
matinv:  3.3     2.6
```

**Comment by JeffreySarnoff** [comment]
alright -- with current master benchmarking on Julia versions 1.1.1, 1.2.0-rel2, 1.3.0-Dev,    
the higher the version, the better the performance (and the current version 1.1.1 does well).

```
  v1.1.1     
     relative speeds
         (32)    (64)

mul:     23.1    19.4
muladd:  21.4    16.1
add:     18.5    10.3
poly:    13.8    20.6
matmul:  11.6    14.4
matlu:   4.6     5.9
matinv:  3.5     2.8
```
```
  v1.2.0     
     relative speeds
         (32)    (64)

mul:     23.1    20.6
muladd:  21.2    17.7
add:     18.2    15.6
poly:    14.2    22.1
matmul:  11.9    13.3
matlu:   4.3     5.6
matinv:  3.5     2.6
```
```
  v1.3.0-Dev     
     relative speeds
         (32)    (64)

mul:     27.9    22.7
muladd:  21.6    19.1
add:     19.2    16.0
poly:    14.0    21.9
matmul:  11.8    13.9
matlu:   4.9     6.1
matinv:  3.5     2.7
````

**Comment by JeffreySarnoff** [comment]
fyi I am going to close most of the issues prior to announcing this tomorrow (acknowledging your contribution).
