### ISSUE TITLE
Seg fault on different eltypes

### ISSUE THREAD

**Issue by mcognetta** [JeffreySarnoff/FastRationals.jl#5]
Currently, adding (and other binary operations) between two `FastRationals` with different backing `Integer` types fails. Presumably, the intended usage is not only between `FastRationals` with the same numerical `eltype`.

MWE:
```julia
julia> x = FastRational{Int32, FastRationals.IsReduced}(3,2)
3//2

julia> typeof(x)
FastRational{Int32,FastRationals.IsReduced}

julia> y = FastRational(3,2)
3//2

julia> typeof(y)
FastRational{Int64,FastRationals.IsReduced}

julia> x+y
Segmentation fault (core dumped)
```

**Comment by JeffreySarnoff** [comment]
no longer an issue
